[Settings]
startKey=p
stopKey=l

; == Select Your Resolution ==
; ↓ Available Options ↓
; 1280x720 | 1366x768 | 1600x900 | 1920x1080 | 2560x1440
pickRes=1920x1080 

bubbleFarm=true
sellBubbles=false
bubbleSellTime=60
eggOpen=false
fallSafety=true
fallSafetyAmount=8
autoClaimChests=true
VipChest=false
playtimeGiftClaim=true
alienShopBuy=false
blackMarketShopBuy=false
wheelSpinClaim=true
reconnectFeature=true

webhookImage=false
WebhookLink=
WebhookTime=25

disconnectColor=0xFFFFFF

floatingChestTime=15.5
voidChestTime=40.5
infinityChestTime=41.5
playTimeGiftTime=92
alienShopTime=16.5
blackMarketShopTime=240
wheelClaimTime=20.5

gameLoadTime=20
assetLoadTime=5

SoundEffects=true
